###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Mon Aug 29 10:12:54 2022
##  Generated by MIG Version 4.1
##  
##################################################################################################
##  File name :       DDR3_AXI_IF.xdc
##  Details :     Constraints file
##                    FPGA Family:       SPARTAN7
##                    FPGA Part:         XC7S75-FGGA484
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       3077 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K1G8SN-107
## Data Width: 8
## Time Period: 3077
## Data Mask: 1
##################################################################################################

create_clock -period 5 [get_ports sys_clk_i]
          
create_clock -period 5 [get_ports clk_ref_i]
          