-- VHDL Entity access_config_lib.access_config_top.symbol
--
-- Created:
--          by - Administrators.Domain Users (ILQHFAATC1NB295)
--          at - 09:58:44 07/06/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY access_config_top IS
   PORT( 
      clk             : IN     std_logic;
      config_ctl_reg  : IN     std_logic_vector (31 DOWNTO 0);
      din             : IN     STD_LOGIC_VECTOR (63 DOWNTO 0);
      reset           : IN     std_logic;
      reset_fifo      : IN     std_logic;
      so              : IN     std_logic;
      wr_en           : IN     STD_LOGIC;
      CS              : OUT    std_logic;
      SCK             : OUT    std_logic;
      busy            : OUT    std_logic;
      conf_status_reg : OUT    std_logic_vector (15 DOWNTO 0);
      data_out        : OUT    std_logic_vector (63 DOWNTO 0);
      rd_data_count   : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
      si              : OUT    std_logic
   );

-- Declarations

END access_config_top ;

--
-- VHDL Architecture access_config_lib.access_config_top.struct
--
-- Created:
--          by - Administrators.Domain Users (ILQHFAATC1NB295)
--          at - 09:58:44 07/06/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;



ARCHITECTURE struct OF access_config_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL EXE             : std_logic;
   SIGNAL EXE_p           : std_logic;
   SIGNAL IR              : std_logic_vector(7 DOWNTO 0);
   SIGNAL PP              : std_logic;
   SIGNAL PP_CRC_error    : std_logic;
   SIGNAL SCK_aux         : std_logic;
   SIGNAL SCK_ena         : std_logic;
   SIGNAL SPI_busy        : std_logic;
   SIGNAL addr_byte       : std_logic_vector(23 DOWNTO 0);
   SIGNAL addr_byte_p     : std_logic_vector(23 DOWNTO 0);
   SIGNAL capture_r_crc   : std_logic;
   SIGNAL capture_w_crc   : std_logic;
   SIGNAL command         : std_logic_vector(3 DOWNTO 0);
   SIGNAL command_p       : std_logic_vector(3 DOWNTO 0);
   SIGNAL data_in         : std_logic_vector(63 DOWNTO 0);
   SIGNAL load            : std_logic;
   SIGNAL load_fifo       : std_logic;
   SIGNAL next4bytes      : std_logic;
   SIGNAL num_bytes       : std_logic_vector(3 DOWNTO 0);
   SIGNAL rd_data_count_o   : STD_LOGIC_VECTOR(6 DOWNTO 0);
   SIGNAL rd_en           : std_logic;
   SIGNAL rst             : std_logic;
   SIGNAL sel             : std_logic_vector(3 DOWNTO 0);
   SIGNAL shift_IR        : std_logic;
   SIGNAL shift_addr_byte : std_logic;
   SIGNAL shift_data_in   : std_logic;
   SIGNAL shift_data_out  : std_logic;
   SIGNAL shift_ena       : std_logic;
   SIGNAL shift_ena_out   : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL si_internal : std_logic;


   -- Component Declarations
   COMPONENT SPI_SM
   PORT (
      EXE             : IN     std_logic ;
      clk             : IN     std_logic ;
      command         : IN     std_logic_vector (3 DOWNTO 0);
      num_bytes       : IN     std_logic_vector (3 DOWNTO 0);
      reset           : IN     std_logic ;
      CS              : OUT    std_logic ;
      IR              : OUT    std_logic_vector (7 DOWNTO 0);
      SCK_aux         : OUT    std_logic ;
      SCK_ena         : OUT    std_logic ;
      SPI_busy        : OUT    std_logic ;
      load            : OUT    std_logic ;
      sel             : OUT    std_logic_vector (3 DOWNTO 0);
      shift_ena       : OUT    std_logic ;
      shift_ena_out   : OUT    std_logic ;
      shift_IR        : BUFFER std_logic ;
      shift_addr_byte : BUFFER std_logic ;
      shift_data_in   : BUFFER std_logic ;
      shift_data_out  : BUFFER std_logic ;
      PP              : IN     std_logic ;
      next4bytes      : BUFFER std_logic ;
      load_fifo       : BUFFER std_logic ;
      rd_en           : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT crc_calc
   PORT (
      EXE            : IN     std_logic ;
      EXE_p          : IN     std_logic ;
      capture_r_crc  : IN     std_logic ;
      capture_w_crc  : IN     std_logic ;
      clk            : IN     std_logic ;
      command_p      : IN     std_logic_vector (3 DOWNTO 0);
      reset          : IN     std_logic ;
      sel            : IN     std_logic_vector (3 DOWNTO 0);
      shift_data_in  : IN     std_logic ;
      shift_data_out : IN     std_logic ;
      shift_ena      : IN     std_logic ;
      shift_ena_out  : IN     std_logic ;
      si             : IN     std_logic ;
      so             : IN     std_logic ;
      PP_CRC_error   : OUT    std_logic 
   );
   END COMPONENT;
 -- COMPONENT fifo_generator_v9_3
 -- PORT (
 --    din           : IN     STD_LOGIC_VECTOR (63 DOWNTO 0);
 --    rd_clk        : IN     STD_LOGIC;
 --    rd_en         : IN     STD_LOGIC;
 --    rst           : IN     STD_LOGIC;
 --    wr_clk        : IN     STD_LOGIC;
 --    wr_en         : IN     STD_LOGIC;
 --    dout          : OUT    STD_LOGIC_VECTOR (63 DOWNTO 0);
 --    empty         : OUT    STD_LOGIC;
 --    full          : OUT    STD_LOGIC;
 --    rd_data_count : OUT    STD_LOGIC_VECTOR (6 DOWNTO 0)
 -- );
 --  END COMPONENT;
 
   COMPONENT fifo_64x128
  PORT (
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC;                -- !debug: 15/06/2022 was srst
    din : IN STD_LOGIC_VECTOR(63 DOWNTO 0);
    wr_en : IN STD_LOGIC;
    rd_en : IN STD_LOGIC;
    dout : OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
    full : OUT STD_LOGIC;
    empty : OUT STD_LOGIC;
    data_count : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
    wr_rst_busy : out STD_LOGIC;        -- !debug: 15/06/2022 only when async reset
    rd_rst_busy : out STD_LOGIC         -- !debug: 15/06/2022 only when async reset
  );
END COMPONENT;
   
   
   
   COMPONENT mux_shifter
   PORT (
      IR              : IN     std_logic_vector (7 DOWNTO 0);
      SCK_aux         : IN     std_logic ;
      SCK_ena         : IN     std_logic ;
      so              : IN     std_logic ;
      addr_byte       : IN     std_logic_vector (23 DOWNTO 0);
      clk             : IN     std_logic ;
      data_in         : IN     std_logic_vector (63 DOWNTO 0);
      load            : IN     std_logic ;
      reset           : IN     std_logic ;
      sel             : IN     std_logic_vector (3 DOWNTO 0);
      shift_IR        : IN     std_logic ;
      shift_addr_byte : IN     std_logic ;
      shift_data_in   : IN     std_logic ;
      shift_data_out  : IN     std_logic ;
      shift_ena       : IN     std_logic ;
      shift_ena_out   : IN     std_logic ;
      SCK             : OUT    std_logic ;
      si              : OUT    std_logic ;
      data_out        : OUT    std_logic_vector (63 DOWNTO 0);
      next4bytes      : IN     std_logic ;
      load_fifo       : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT prime_dec_sm
   PORT (
      EXE_p           : IN     std_logic ;
      PP_CRC_error    : IN     std_logic ;
      SPI_busy        : IN     std_logic ;
      addr_byte_p     : IN     std_logic_vector (23 DOWNTO 0);
      clk             : IN     std_logic ;
      command_p       : IN     std_logic_vector (3 DOWNTO 0);
      rd_data_count   : IN     STD_LOGIC_VECTOR (6 DOWNTO 0);
      reset           : IN     std_logic ;
      reset_fifo      : IN     std_logic ;
      EXE             : OUT    std_logic ;
      PP              : OUT    std_logic ;
      addr_byte       : OUT    std_logic_vector (23 DOWNTO 0);
      busy            : OUT    std_logic ;
      capture_r_crc   : OUT    std_logic ;
      capture_w_crc   : OUT    std_logic ;
      command         : OUT    std_logic_vector (3 DOWNTO 0);
      conf_status_reg : OUT    std_logic_vector (15 DOWNTO 0);
      num_bytes       : OUT    std_logic_vector (3 DOWNTO 0)
   );
   END COMPONENT;

   


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 2 eb2
   -- eb2 2                                        
   rst<= not reset or reset_fifo;
   

   -- HDL Embedded Text Block 3 eb3
   -- eb3 3 
   addr_byte_p<= config_ctl_reg(23 downto 0);
   command_p<= config_ctl_reg(27 downto 24);
   EXE_p<=  config_ctl_reg(31);                                       


   -- Instance port mappings.
   U_0 : SPI_SM
      PORT MAP (
         EXE             => EXE,
         clk             => clk,
         command         => command,
         num_bytes       => num_bytes,
         reset           => reset,
         CS              => CS,
         IR              => IR,
         SCK_aux         => SCK_aux,
         SCK_ena         => SCK_ena,
         SPI_busy        => SPI_busy,
         load            => load,
         sel             => sel,
         shift_ena       => shift_ena,
         shift_ena_out   => shift_ena_out,
         shift_IR        => shift_IR,
         shift_addr_byte => shift_addr_byte,
         shift_data_in   => shift_data_in,
         shift_data_out  => shift_data_out,
         PP              => PP,
         next4bytes      => next4bytes,
         load_fifo       => load_fifo,
         rd_en           => rd_en
      );
   U_3 : crc_calc
      PORT MAP (
         EXE            => EXE,
         EXE_p          => EXE_p,
         capture_r_crc  => capture_r_crc,
         capture_w_crc  => capture_w_crc,
         clk            => clk,
         command_p      => command_p,
         reset          => reset,
         sel            => sel,
         shift_data_in  => shift_data_in,
         shift_data_out => shift_data_out,
         shift_ena      => shift_ena,
         shift_ena_out  => shift_ena_out,
         si             => si_internal,
         so             => so,
         PP_CRC_error   => PP_CRC_error
      );
	  

U_5 : fifo_64x128
  PORT MAP (
    clk => clk,
    rst => rst,
    din => din,
    wr_en => wr_en,
    rd_en => rd_en,
    dout => data_in,
    full => OPEN,
    empty => OPEN,
    data_count => rd_data_count_o,
    wr_rst_busy => OPEN,  -- !debug: 15/06/2022 only when async reset
    rd_rst_busy => OPEN  -- !debug: 15/06/2022 only when async reset
  );	  
	  
	  
   U_1 : mux_shifter
      PORT MAP (
         IR              => IR,
         SCK_aux         => SCK_aux,
         SCK_ena         => SCK_ena,
         so              => so,
         addr_byte       => addr_byte,
         clk             => clk,
         data_in         => data_in,
         load            => load,
         reset           => reset,
         sel             => sel,
         shift_IR        => shift_IR,
         shift_addr_byte => shift_addr_byte,
         shift_data_in   => shift_data_in,
         shift_data_out  => shift_data_out,
         shift_ena       => shift_ena,
         shift_ena_out   => shift_ena_out,
         SCK             => SCK,
         si              => si_internal,
         data_out        => data_out,
         next4bytes      => next4bytes,
         load_fifo       => load_fifo
      );
   U_2 : prime_dec_sm
      PORT MAP (
         EXE_p           => EXE_p,
         PP_CRC_error    => PP_CRC_error,
         SPI_busy        => SPI_busy,
         addr_byte_p     => addr_byte_p,
         clk             => clk,
         command_p       => command_p,
         rd_data_count   => rd_data_count_o, --22/09
         reset           => reset,
         reset_fifo      => reset_fifo,
         EXE             => EXE,
         PP              => PP,
         addr_byte       => addr_byte,
         busy            => busy,
         capture_r_crc   => capture_r_crc,
         capture_w_crc   => capture_w_crc,
         command         => command,
         conf_status_reg => conf_status_reg,
         num_bytes       => num_bytes
      );

   -- Implicit buffered output assignments
   si <= si_internal;
   rd_data_count   <= rd_data_count_o ;
END struct;
