library ieee;
USE IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.NUMERIC_STD.ALL;


ENTITY clk_80_160MHz IS
Port(
	Clk_IN: IN STD_LOGIC;
	RST: IN STD_LOGIC; 
	CLK_SEL: IN STD_LOGIC_VECTOR(3 DOWNTO 0); 
	Clk_OUT: OUT STD_LOGIC);

END clk_80_160MHz;

ARCHITECTURE clk_80_160MHz_arc OF clk_80_160MHz IS
SIGNAL CLK_COUNTER: STD_LOGIC_VECTOR(3 DOWNTO 0):=(OTHERS=>'0'); 
BEGIN
p1_COUNTER:PROCESS(Clk_IN,RST)
BEGIN
IF RST='1' THEN
	CLK_COUNTER<=(OTHERS=>'0'); 
ELSIF RISING_EDGE(Clk_IN) THEN
	
	IF CLK_COUNTER=X"3" THEN
		CLK_COUNTER<=(OTHERS=>'0');
	ELSE
		CLK_COUNTER<=CLK_COUNTER+1;
 
	END IF;
	
END IF;
END PROCESS;

P2_SEND_CLK_OUT: PROCESS(Clk_IN)
BEGIN 
IF RISING_EDGE(Clk_IN)  THEN
	CASE CLK_SEL IS

		WHEN X"7"=>--320Mhz
			Clk_OUT<=Clk_In;
		WHEN X"5"=>NULL;
		WHEN X"3"=>--160Mhz
			Clk_OUT<=CLK_COUNTER(0);
		WHEN X"1"=>--80MHz
			Clk_OUT<=CLK_COUNTER(1);
		WHEN OTHERS=>--320Mhz
			Clk_OUT<=Clk_In;

		END CASE;
END IF;
END PROCESS;
END clk_80_160MHz_arc;
