onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider TB
add wave -noupdate /register_data_if_tb/CLK_COUNTER
add wave -noupdate /register_data_if_tb/S_Clk_Rate
add wave -noupdate /register_data_if_tb/S_SClk
add wave -noupdate /register_data_if_tb/S_SDO
add wave -noupdate /register_data_if_tb/S_SCn
add wave -noupdate /register_data_if_tb/S_rst
add wave -noupdate /register_data_if_tb/S_SDI
add wave -noupdate /register_data_if_tb/S_SYNC
add wave -noupdate /register_data_if_tb/S_Aclk
add wave -noupdate /register_data_if_tb/S_D_start
add wave -noupdate /register_data_if_tb/S_Discard
add wave -noupdate /register_data_if_tb/S_Operation_Mode_Initialized
add wave -noupdate /register_data_if_tb/S_Data1_Out
add wave -noupdate /register_data_if_tb/S_Data2_Out
add wave -noupdate /register_data_if_tb/num_data_lines
add wave -noupdate /register_data_if_tb/legacy_mode
add wave -noupdate /register_data_if_tb/data_word_length
add wave -noupdate /register_data_if_tb/Footer_disable
add wave -noupdate /register_data_if_tb/Pres_Idle_Word_D1_Seial_In
add wave -noupdate /register_data_if_tb/Pres_Idle_Word_D2_Seial_In
add wave -noupdate /register_data_if_tb/Pres_Idle_Word_D1_As_Vec
add wave -noupdate /register_data_if_tb/Pres_Idle_Word_D2_As_Vec
add wave -noupdate /register_data_if_tb/Pres_Idle_Word_Bit_Counter
add wave -noupdate /register_data_if_tb/Local_Bit_Counter
add wave -noupdate /register_data_if_tb/Pres_Idles_Word_Counter
add wave -noupdate /register_data_if_tb/Idles_Word_Completed
add wave -noupdate /register_data_if_tb/Data_word_length_bits_amount
add wave -noupdate /register_data_if_tb/Pres_Start_Word
add wave -noupdate /register_data_if_tb/Pres_Start_Word0_As_Vec
add wave -noupdate /register_data_if_tb/Pres_Start_Word1_As_Vec
add wave -noupdate /register_data_if_tb/Pres_Start_Word2_As_Vec
add wave -noupdate /register_data_if_tb/Pres_Start_Word_Counter
add wave -noupdate /register_data_if_tb/TestsTypes_ver
add wave -noupdate /register_data_if_tb/Word_test_0007
add wave -noupdate /register_data_if_tb/Word_test_0ad3
add wave -noupdate /register_data_if_tb/Word_test_2d50
add wave -noupdate /register_data_if_tb/Word_test_0062
add wave -noupdate /register_data_if_tb/Word_test_0351
add wave -noupdate /register_data_if_tb/Word_test_0000
add wave -noupdate /register_data_if_tb/TB_Cur_state
add wave -noupdate /register_data_if_tb/TB_BIT_COUNTER
add wave -noupdate /register_data_if_tb/ADDR_Pointer
add wave -noupdate /register_data_if_tb/TB_BANK_BUFFER
add wave -noupdate /register_data_if_tb/ADDR_ODD_TEST
add wave -noupdate /register_data_if_tb/DATA_ODD_TEST
add wave -noupdate /register_data_if_tb/IDLE_Wait
add wave -noupdate /register_data_if_tb/Time_counter
add wave -noupdate /register_data_if_tb/SPI_READ_WR_STATUS
add wave -noupdate /register_data_if_tb/do_not_sample
add wave -noupdate /register_data_if_tb/Sampling_SDI_In
add wave -noupdate /register_data_if_tb/Sampling_SDI_In_ADDR
add wave -noupdate /register_data_if_tb/Sampling_SDI_In_Data
add wave -noupdate /register_data_if_tb/Sampling_ADDR
add wave -noupdate /register_data_if_tb/Sampling_Data
add wave -noupdate -radix decimal /register_data_if_tb/ASIC_DATA_line_1
add wave -noupdate /register_data_if_tb/ASIC_DATA_line_2
add wave -noupdate /register_data_if_tb/bit_Data_counter
add wave -noupdate /register_data_if_tb/Word_Data_counter
add wave -noupdate /register_data_if_tb/Pres_ASIC_DATA_line_1_As_Vec
add wave -noupdate /register_data_if_tb/Pres_ASIC_DATA_line_2_As_Vec
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_1_Completed
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_2_Completed
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_3_Completed
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_4_Completed
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_5_Completed
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_6_Completed
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_line1
add wave -noupdate /register_data_if_tb/Pres_LVDS_FOOTER_line1
add wave -noupdate /register_data_if_tb/LVDS_FOOTER_line2
add wave -noupdate /register_data_if_tb/Pres_LVDS_FOOTER_line2
add wave -noupdate /register_data_if_tb/CRC_line1
add wave -noupdate /register_data_if_tb/CRC_line2
add wave -noupdate /register_data_if_tb/Pres_CRC_line1_As_Vec
add wave -noupdate /register_data_if_tb/Pres_CRC_line2_As_Vec
add wave -noupdate /register_data_if_tb/S_Test_Plan_Data_From_File
add wave -noupdate /register_data_if_tb/EN_clk_counter
add wave -noupdate /register_data_if_tb/EN_PULSE
add wave -noupdate /register_data_if_tb/EN_Cur_state_type
add wave -noupdate /register_data_if_tb/S_Clk_DIV
add wave -noupdate /register_data_if_tb/cal_Cur_state
add wave -noupdate /register_data_if_tb/Word_test_0011
add wave -noupdate /register_data_if_tb/Word_test_0111
add wave -noupdate /register_data_if_tb/Word_test_1011
add wave -noupdate /register_data_if_tb/Word_test_1111
add wave -noupdate /register_data_if_tb/RUN_CAL_PRO
add wave -noupdate /register_data_if_tb/Cal_BIT_COUNTER
add wave -noupdate /register_data_if_tb/Cal_ADDR_Pointer
add wave -noupdate /register_data_if_tb/Cal_BANK_BUFFER
add wave -noupdate /register_data_if_tb/Cal_Pulse_counter
add wave -noupdate /register_data_if_tb/Cal_ADDR_ODD_TEST
add wave -noupdate /register_data_if_tb/Cal_DATA_ODD_TEST
add wave -noupdate /register_data_if_tb/Max_Idle_Word_Amount
add wave -noupdate -divider {U1 REGISTER IF}
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/SClk
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/SDO
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/SCn
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/Rst
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/SDI
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/Calibration
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/set_up
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/num_data_lines
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/legacy_mode
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/data_word_length
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/idle_word
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/start_delay_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/start_delay_17DownTo15
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/scrambler_rst
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/scrambler_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/footer_disable
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/tm_aci_data
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/raw_data_bypass
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/hclk_div_cfg
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/itest_dis
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/d_start_oen
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/data1_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/data2_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/clk_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/daisy_chain
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/LVDS_start_word_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/LVDS_start_word_29DownTo15
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/LVDS_start_word_39DownTo30
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_RD_WR
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_ADDR_BUS
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_DATA_BUS_SDI_WR
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_DATA_BUS_SDI_READ
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_Calibration_done
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_DONE_WRITE
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_LVDS_CONFIG_1
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_LVDS_CONFIG_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_LVDS_CONFIG_3
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_Clock_CTRL
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_PADS_CONFIG_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_LVDS_START_WORD_0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_LVDS_START_WORD_1
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/S_LVDS_START_WORD_2
add wave -noupdate -divider {U2 R_W_REG}
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/Calibration_done
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/START_AUTO_CAL
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/CALIB_CONFIG_0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/CALIB_CONFIG_1
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/OFFV_CAL_RESULTS
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/CALIB_CONFIG_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/CALIB_CONFIG_3
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/CALIB_MONITOR
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_1
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_1
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_3
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_3
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_4
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_4
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_5
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_5
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_6
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_6
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_7
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_7
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_8
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_8
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_9
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_9
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_10
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_10
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_11
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_11
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_12
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_12
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_13
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_13
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_14
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_14
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_15
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_15
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_16
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_16
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_17
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_17
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_18
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_18
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_19
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_19
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_20
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_20
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_21
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_21
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_22
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_22
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_23
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_23
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_24
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_24
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_25
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_25
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_26
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_26
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_27
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_27
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_28
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_28
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_29
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_29
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_30
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_30
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_31
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_31
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_32
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_32
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_33
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_33
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_34
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_34
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_35
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_35
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_36
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_36
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_37
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_37
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_38
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_38
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_39
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_39
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_40
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_40
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_41
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_41
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_42
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_42
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_43
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_43
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_44
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_44
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_45
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_45
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_46
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_46
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_47
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_47
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_48
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_48
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_49
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_49
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_50
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_50
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_51
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_51
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_52
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_52
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_53
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_53
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_54
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_54
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_55
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_55
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_56
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_56
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_57
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_57
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_58
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_58
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_59
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_59
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_60
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_60
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_61
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_61
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_62
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_62
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_63
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_63
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_64
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_64
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_65
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_65
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_66
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_66
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_67
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_67
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_68
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_68
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_69
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_69
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_70
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_70
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_71
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_71
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_72
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_72
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_73
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_73
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_74
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_74
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_75
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_75
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_76
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_76
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_77
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_77
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_78
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_78
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_79
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_79
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_80
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_80
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_81
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_81
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_82
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_82
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_83
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_83
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_84
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_84
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_85
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_85
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_86
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_86
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_87
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_87
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_88
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_88
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_89
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_89
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_90
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_90
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_91
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_91
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_92
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_92
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_93
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_93
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_94
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_94
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_95
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_95
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_96
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_96
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_97
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_97
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_98
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_98
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_99
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_99
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_100
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_100
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_101
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_101
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_102
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_102
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_103
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_103
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_104
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_104
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_105
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_105
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_106
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_106
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_107
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_107
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_108
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_108
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_109
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_109
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_110
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_110
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_111
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_111
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_112
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_112
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_113
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_113
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_114
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_114
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_115
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_115
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_116
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_116
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_117
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_117
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_118
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_118
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_119
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_119
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_120
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_120
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_121
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_121
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_122
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_122
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_123
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_123
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_124
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_124
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_125
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_125
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_126
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_126
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_127
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_127
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_128
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_128
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_129
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_129
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_130
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_130
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_131
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_131
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_132
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_132
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_133
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_133
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_134
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_134
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_135
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_135
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_136
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_136
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_137
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_137
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_138
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_138
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_139
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_139
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_140
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_140
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_141
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_141
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_142
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_142
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_143
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_143
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_144
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_144
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_145
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_145
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_146
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_146
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_147
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_147
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_148
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_148
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_149
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_149
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_150
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_150
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_151
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_151
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_152
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_152
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_153
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_153
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_154
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_154
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_155
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_155
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_156
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_156
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_157
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_157
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_158
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_158
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_159
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_159
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_160
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_160
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_161
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_161
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_162
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_162
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_163
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_163
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_164
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_164
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_165
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_165
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_166
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_166
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_167
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_167
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_168
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_168
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_169
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_169
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_170
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_170
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_171
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_171
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_172
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_172
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_173
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_173
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_174
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_174
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_175
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_175
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_176
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_176
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_177
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_177
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_178
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_178
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_179
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_179
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_180
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_180
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_181
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_181
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_182
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_182
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_183
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_183
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_184
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_184
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_185
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_185
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_186
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_186
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_187
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_187
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_188
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_188
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_189
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_189
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_190
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_190
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_191
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_191
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_192
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_192
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_193
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_193
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_194
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_194
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_195
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_195
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_196
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_196
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_197
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_197
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_198
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_198
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_199
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_199
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_200
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_200
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_201
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_201
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_202
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_202
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_203
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_203
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_204
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_204
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_205
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_205
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_206
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_206
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_207
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_207
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_208
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_208
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_209
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_209
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_210
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_210
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_211
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_211
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_212
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_212
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_213
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_213
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_214
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_214
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_215
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_215
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_216
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_216
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_217
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_217
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_218
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_218
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_219
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_219
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_220
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_220
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_221
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_221
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_222
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_222
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_223
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_223
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_224
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_224
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_225
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_225
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_226
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_226
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_227
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_227
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_228
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_228
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_229
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_229
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_230
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_230
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_231
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_231
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_232
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_232
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_233
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_233
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_234
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_234
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_235
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_235
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_236
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_236
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_237
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_237
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_238
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_238
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_239
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_239
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_240
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_240
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_241
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_241
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_242
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_242
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_243
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_243
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_244
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_244
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_245
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_245
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_246
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_246
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_247
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_247
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_248
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_248
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_249
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_249
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_250
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_250
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_251
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_251
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_252
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_252
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_253
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_253
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_254
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_254
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP1_255
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U2_R_W_Bank_Reg/LIN_CAL_QP2_255
add wave -noupdate -divider {U3 CONFIGURATION}
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/Rst
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/SClk
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_CONFIG_1
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_CONFIG_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_CONFIG_3
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/Clock_CTRL
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/PADS_CONFIG_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_START_WORD_0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_START_WORD_1
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_START_WORD_2
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/DONE_WRITE
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/Calibration_done
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/Calibration
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/OperationMode
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/set_up
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/num_data_lines
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/legacy_mode
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/data_word_length
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/idle_word
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/start_delay_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/start_delay_17DownTo15
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/scrambler_rst
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/scrambler_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/footer_disable
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/tm_aci_data
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/raw_data_bypass
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/hclk_div_cfg
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/itest_dis
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/d_start_oen
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/data1_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/data2_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/clk_en
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/daisy_chain
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_START_WORD_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_START_WORD_29DownTo15
add wave -noupdate /register_data_if_tb/DUT/U1_Register_IF/U3_Configuration_Registers/LVDS_START_WORD_39DownTo30
add wave -noupdate -divider {U2 DATA_IF}
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/SCLK
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/RST
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/SYNC
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/ACLK
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/D_START
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Discard
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/OperationMode
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/set_up
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Calibration
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/num_data_lines
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/legacy_mode
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/data_word_length
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/idle_word
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/start_delay_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/start_delay_17DownTo15
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/scrambler_rst
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/scrambler_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/footer_disable
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/tm_aci_data
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/raw_data_bypass
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/hclk_div_cfg
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/itest_dis
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/d_start_oen
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/data1_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/data2_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/clk_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/daisy_chain
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_start_word_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_start_word_29DownTo15
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_start_word_39DownTo30
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Operation_Mode_Initialized
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/DATA1_Out
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/DATA2_Out
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Data_IF_Cur_state_type
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Data_word_length_bits_amount
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Clk_Rate
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/CLK_COUNTER
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Clk_Rate
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Clk_Rate_Last_Sample
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Sync_Last_sample
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Idles_Word_Sent_Counter
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Idle_Bit_Counter
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Idle_word_completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_tDSTART_DLY
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Start_Word_Bit_Counter
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_LVDS_start_word
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_LVDS_start_word_completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Data1_out_Vec
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/channel_number
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/Xray_res_Counter
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Xray_Data1
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Xray_Data2
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_Bit_Pointer
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_Bit_Max_Bit
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_1_Completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_2_Completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_3_Completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_4_Completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_5_Completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/LVDS_FOOTER_6_Completed
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/XRAY_DATA
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/lines_amount
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_num_data_lines
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_legacy_mode
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_data_word_length
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_idle_word
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_idle_word_static
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_start_delay_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_start_delay_17DownTo15
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_scrambler_rst
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_scrambler_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_footer_disable
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_tm_aci_data
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_raw_data_bypass
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_hclk_div_cfg
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_itest_dis
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_d_start_oen
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_data1_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_data2_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_clk_en
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_daisy_chain
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_LVDS_start_word_14DownTo0
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_LVDS_start_word_29DownTo15
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_LVDS_start_word_39DownTo30
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_footer_1_reg_addr
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_footer_2_reg_addr
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_footer_3_reg_addr
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_footer_4_reg_addr
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_footer_5_reg_addr
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_footer_6_reg_addr
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Xray_Data1_From_File
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Xray_Line_Data1_From_File
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Xray_Line_Data2_From_File
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/crc_calc_1
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/crc_calc_2
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/CRC_Bit_Counter
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/EN_clk_counter
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/EN_PULSE
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/EN_Cur_state_type
add wave -noupdate /register_data_if_tb/DUT/U2_DATA_IF/S_Clk_DIV
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {40174 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 178
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {1854562 ns} {2007655 ns}
