set_property IOSTANDARD LVCMOS18 [get_ports {ACLK[0]}]
set_property DRIVE 8 [get_ports {ACLK[0]}]
set_property SLEW SLOW [get_ports {ACLK[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ACLK[1]}]
set_property DRIVE 8 [get_ports {ACLK[1]}]
set_property SLEW SLOW [get_ports {ACLK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ACLK[2]}]
set_property DRIVE 8 [get_ports {ACLK[2]}]
set_property SLEW SLOW [get_ports {ACLK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ACLK[3]}]
set_property DRIVE 8 [get_ports {ACLK[3]}]
set_property SLEW SLOW [get_ports {ACLK[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports ACLK_MASTER]
set_property IOSTANDARD LVDS_25 [get_ports ACLK_MASTER_N]
set_property IOSTANDARD LVDS_25 [get_ports Sync_P]
set_property IOSTANDARD LVDS_25 [get_ports Sync_N]
set_property IOSTANDARD LVCMOS18 [get_ports {DISCARD[0]}]
set_property DRIVE 8 [get_ports {DISCARD[0]}]
set_property SLEW SLOW [get_ports {DISCARD[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISCARD[1]}]
set_property DRIVE 8 [get_ports {DISCARD[1]}]
set_property SLEW SLOW [get_ports {DISCARD[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISCARD[2]}]
set_property DRIVE 8 [get_ports {DISCARD[2]}]
set_property SLEW SLOW [get_ports {DISCARD[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISCARD[3]}]
set_property DRIVE 8 [get_ports {DISCARD[3]}]
set_property SLEW SLOW [get_ports {DISCARD[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {HW_REV[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {HW_REV[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {HW_REV[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {HW_REV[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA_OUT[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA_OUT_N[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {AUX_DATA_IN[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {AUX_DATA_IN_N[*]}]
#set_property IOSTANDARD LVDS_25 [get_ports {TILES_CLK_N[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RESETn[0]}]
set_property DRIVE 8 [get_ports {RESETn[0]}]
set_property SLEW SLOW [get_ports {RESETn[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RESETn[1]}]
set_property DRIVE 8 [get_ports {RESETn[1]}]
set_property SLEW SLOW [get_ports {RESETn[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RESETn[2]}]
set_property DRIVE 8 [get_ports {RESETn[2]}]
set_property SLEW SLOW [get_ports {RESETn[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RESETn[3]}]
set_property DRIVE 8 [get_ports {RESETn[3]}]
set_property SLEW SLOW [get_ports {RESETn[3]}]
# set_property IOSTANDARD LVCMOS25 [get_ports Sig_1]
set_property IOSTANDARD LVCMOS18 [get_ports Sig_2]
set_property IOSTANDARD LVCMOS18 [get_ports {SCLK[0]}]
set_property DRIVE 8 [get_ports {SCLK[0]}]
set_property SLEW SLOW [get_ports {SCLK[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCLK[1]}]
set_property DRIVE 8 [get_ports {SCLK[1]}]
set_property SLEW SLOW [get_ports {SCLK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCLK[2]}]
set_property DRIVE 8 [get_ports {SCLK[2]}]
set_property SLEW SLOW [get_ports {SCLK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCLK[3]}]
set_property DRIVE 8 [get_ports {SCLK[3]}]
set_property SLEW SLOW [get_ports {SCLK[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SCL[0]}]
set_property DRIVE 4 [get_ports {SCL[0]}]
set_property SLEW SLOW [get_ports {SCL[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SCL[1]}]
set_property DRIVE 4 [get_ports {SCL[1]}]
set_property SLEW SLOW [get_ports {SCL[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS1[0]}]
set_property DRIVE 8 [get_ports {SCS1[0]}]
set_property SLEW SLOW [get_ports {SCS1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS1[1]}]
set_property DRIVE 8 [get_ports {SCS1[1]}]
set_property SLEW SLOW [get_ports {SCS1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS1[2]}]
set_property DRIVE 8 [get_ports {SCS1[2]}]
set_property SLEW SLOW [get_ports {SCS1[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS1[3]}]
set_property DRIVE 8 [get_ports {SCS1[3]}]
set_property SLEW SLOW [get_ports {SCS1[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS2[0]}]
set_property DRIVE 8 [get_ports {SCS2[0]}]
set_property SLEW SLOW [get_ports {SCS2[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS2[1]}]
set_property DRIVE 8 [get_ports {SCS2[1]}]
set_property SLEW SLOW [get_ports {SCS2[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS2[2]}]
set_property DRIVE 8 [get_ports {SCS2[2]}]
set_property SLEW SLOW [get_ports {SCS2[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SCS2[3]}]
set_property DRIVE 8 [get_ports {SCS2[3]}]
set_property SLEW SLOW [get_ports {SCS2[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SDA[0]}]
set_property DRIVE 4 [get_ports {SDA[0]}]
set_property SLEW SLOW [get_ports {SDA[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SDA[1]}]
set_property DRIVE 4 [get_ports {SDA[1]}]
set_property SLEW SLOW [get_ports {SDA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDI[0]}]
set_property DRIVE 8 [get_ports {SDI[0]}]
set_property SLEW SLOW [get_ports {SDI[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDI[1]}]
set_property DRIVE 8 [get_ports {SDI[1]}]
set_property SLEW SLOW [get_ports {SDI[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDI[2]}]
set_property DRIVE 8 [get_ports {SDI[2]}]
set_property SLEW SLOW [get_ports {SDI[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDI[3]}]
set_property DRIVE 8 [get_ports {SDI[3]}]
set_property SLEW SLOW [get_ports {SDI[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDO[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SDO[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SYNC[0]}]
set_property DRIVE 8 [get_ports {SYNC[0]}]
set_property SLEW SLOW [get_ports {SYNC[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SYNC[1]}]
set_property DRIVE 8 [get_ports {SYNC[1]}]
set_property SLEW SLOW [get_ports {SYNC[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SYNC[2]}]
set_property DRIVE 8 [get_ports {SYNC[2]}]
set_property SLEW SLOW [get_ports {SYNC[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SYNC[3]}]
set_property DRIVE 8 [get_ports {SYNC[3]}]
set_property SLEW SLOW [get_ports {SYNC[3]}]
set_property DIFF_TERM true [get_ports {AUX_DATA_IN[*]}]

set_property IOSTANDARD LVDS_25 [get_ports Buffer_P]
set_property IOSTANDARD LVDS_25 [get_ports Buffer_N]
set_property DIFF_TERM TRUE [get_ports Buffer_P]
set_property DIFF_TERM TRUE [get_ports Buffer_N]

set_property IOSTANDARD LVDS_25 [get_ports Reg_in_P]
set_property IOSTANDARD LVDS_25 [get_ports Reg_in_N]
set_property DIFF_TERM TRUE [get_ports Reg_in_P]
set_property DIFF_TERM TRUE [get_ports Reg_in_N]

set_property IOSTANDARD LVDS_25 [get_ports Reg_out_P]
set_property IOSTANDARD LVDS_25 [get_ports Reg_out_N]
#set_property IOSTANDARD LVDS_25 [get_ports P2P_RCOM2TMCOR]
#set_property IOSTANDARD LVDS_25 [get_ports P2P_RCOM2TMCOR_N]
#set_property DIFF_TERM TRUE [get_ports P2P_RCOM2TMCOR]

set_property IOSTANDARD LVCMOS25 [get_ports RESET]
set_property IOSTANDARD LVDS_25 [get_ports Diag_out_P]
set_property IOSTANDARD LVDS_25 [get_ports Diag_out_N]
#set_property DIFF_TERM TRUE [get_ports Diag_out_P]
#set_property DIFF_TERM TRUE [get_ports Diag_out_N]

#set_property IOSTANDARD LVCMOS25 [get_ports Splitter_RCOM2TMCOR]
set_property IOSTANDARD LVDS_25 [get_ports Aux_Reg_out_P]
set_property IOSTANDARD LVDS_25 [get_ports Aux_Reg_out_N]
#set_property DIFF_TERM TRUE [get_ports Aux_Reg_out_P]
#set_property DIFF_TERM TRUE [get_ports Aux_Reg_out_N]
set_property IOSTANDARD LVDS_25 [get_ports Aux_Reg_in_P]
set_property IOSTANDARD LVDS_25 [get_ports Aux_Reg_in_N]
set_property DIFF_TERM TRUE [get_ports Aux_Reg_in_P]
set_property DIFF_TERM TRUE [get_ports Aux_Reg_in_N]

set_property IOSTANDARD LVDS_25 [get_ports Diag_in_P]
set_property IOSTANDARD LVDS_25 [get_ports Diag_in_N]
set_property IOSTANDARD LVDS_25 [get_ports Aux_Diag_in_P]
set_property IOSTANDARD LVDS_25 [get_ports Aux_Diag_in_N]
set_property DIFF_TERM TRUE [get_ports Aux_Diag_in_P]
set_property DIFF_TERM TRUE [get_ports Aux_Diag_in_N]

#set_property IOSTANDARD LVCMOS25 [get_ports Aux_Sig_1]
set_property IOSTANDARD LVCMOS18 [get_ports Aux_Sig_2]
#set_property IOSTANDARD LVDS_25 [get_ports P2P_RCOM2TMCOR_s]
#set_property IOSTANDARD LVDS_25 [get_ports P2P_RCOM2TMCOR_s_N]
set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_CLK0n]
set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_CLK1n]
set_property DRIVE 8 [get_ports DISABLE_CLK0n]
set_property DRIVE 8 [get_ports DISABLE_CLK1n]
set_property SLEW SLOW [get_ports DISABLE_CLK0n]
set_property SLEW SLOW [get_ports DISABLE_CLK1n]
#set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_CLK12]
#set_property DRIVE 8 [get_ports DISABLE_CLK12]
#set_property SLEW SLOW [get_ports DISABLE_CLK12]
#set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_DVDD1n]
#set_property DRIVE 8 [get_ports DISABLE_DVDD1n]
#set_property SLEW SLOW [get_ports DISABLE_DVDD1n]
set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_SLAVEn]
set_property DRIVE 8 [get_ports DISABLE_SLAVEn]
set_property SLEW SLOW [get_ports DISABLE_SLAVEn]
set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_APOSn]
set_property DRIVE 8 [get_ports DISABLE_APOSn]
set_property SLEW SLOW [get_ports DISABLE_APOSn]
set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_ANEGn]
set_property DRIVE 8 [get_ports DISABLE_ANEGn]
set_property SLEW SLOW [get_ports DISABLE_ANEGn]
#set_property IOSTANDARD LVCMOS25 [get_ports DISABLE_DVDD2n]
#set_property DRIVE 8 [get_ports DISABLE_DVDD2n]
#set_property SLEW SLOW [get_ports DISABLE_DVDD2n]
set_property IOSTANDARD LVCMOS25 [get_ports HEATER_1]
set_property DRIVE 8 [get_ports HEATER_1]
set_property SLEW SLOW [get_ports HEATER_1]
set_property IOSTANDARD LVCMOS25 [get_ports HEATER_2]
set_property DRIVE 8 [get_ports HEATER_2]
set_property SLEW SLOW [get_ports HEATER_2]

set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 16 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
#set_property BITSTREAM.GENERAL.SYSMONPOWERDOWN ENABLE [current_design]
#set_property BITSTREAM.GENERAL.JTAG_XADC DISABLE [current_design]
set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]
# 22/02/2023 MultiBoot
#set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 32'h003C0000 [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]

set_property IOSTANDARD LVDS_25 [get_ports {DATA1[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA1[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA1[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA1[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA2[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA2[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA2[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {DATA2[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ACO[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ACO[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ACO[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ACO[0]}]
set_property DIFF_TERM true [get_ports {ACO[*]}]
set_property DIFF_TERM TRUE [get_ports {ACO_N[3]}]
set_property DIFF_TERM TRUE [get_ports {ACO_N[2]}]
set_property DIFF_TERM TRUE [get_ports {ACO_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ACO_N[0]}]
set_property DIFF_TERM true [get_ports {DATA1[*]}]
set_property DIFF_TERM TRUE [get_ports {DATA1_N[3]}]
set_property DIFF_TERM TRUE [get_ports {DATA1_N[2]}]
set_property DIFF_TERM TRUE [get_ports {DATA1_N[1]}]
set_property DIFF_TERM TRUE [get_ports {DATA1_N[0]}]
set_property DIFF_TERM true [get_ports {DATA2[*]}]
set_property DIFF_TERM TRUE [get_ports {DATA2_N[3]}]
set_property DIFF_TERM TRUE [get_ports {DATA2_N[2]}]
set_property DIFF_TERM TRUE [get_ports {DATA2_N[1]}]
set_property DIFF_TERM TRUE [get_ports {DATA2_N[0]}]
#set_property DIFF_TERM TRUE [get_ports {MCLK[1]}]
#set_property DIFF_TERM TRUE [get_ports {MCLK_N[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {D_START[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_START[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_START[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {D_START[0]}]
#set_property IOSTANDARD LVDS_25 [get_ports PLL_CLKOUT]

#set_property PACKAGE_PIN A10 [get_ports Aux_Buffer_P]
#set_property PACKAGE_PIN B11 [get_ports Aux_Diag_out_P]
#set_property PACKAGE_PIN A11 [get_ports Aux_Diag_out_N]


set_property IOSTANDARD LVCMOS25 [get_ports {STATUS_LEDS[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {STATUS_LEDS[1]}]
#set_property PACKAGE_PIN D10 [get_ports {STATUS_LEDS[0]}]
#set_property PACKAGE_PIN C10 [get_ports {STATUS_LEDS[1]}]
#set_property PACKAGE_PIN C12 [get_ports ACLK_MASTER]

# 09/12/2019 DDR3 IP pins override
# As in core
#set_property PACKAGE_PIN P6 [get_ports {ddr3_dm[0]}]
#set_property PACKAGE_PIN R5 [get_ports {ddr3_dqs_p[0]}]
#set_property PACKAGE_PIN T4 [get_ports {ddr3_dqs_n[0]}]
#set_property PACKAGE_PIN P5 [get_ports {ddr3_dq[0]}]
#set_property PACKAGE_PIN V7 [get_ports {ddr3_dq[1]}]
#set_property PACKAGE_PIN V6 [get_ports {ddr3_dq[2]}]
#set_property PACKAGE_PIN T6 [get_ports {ddr3_dq[3]}]
#set_property PACKAGE_PIN T5 [get_ports {ddr3_dq[4]}]
#set_property PACKAGE_PIN R7 [get_ports {ddr3_dq[5]}]
#set_property PACKAGE_PIN R6 [get_ports {ddr3_dq[6]}]
#set_property PACKAGE_PIN U7 [get_ports {ddr3_dq[7]}]

set_property PULLUP true [get_ports {SCS1[1]}]
set_property PULLUP true [get_ports {SCS1[3]}]
set_property PULLUP true [get_ports {SCS1[2]}]
set_property PULLUP true [get_ports {SCS1[0]}]
set_property PULLUP true [get_ports {SCS2[2]}]
set_property PULLUP true [get_ports {SCS2[0]}]
set_property PULLUP true [get_ports {SCS2[3]}]
set_property PULLUP true [get_ports {SCS2[1]}]

set_property IOSTANDARD LVCMOS25 [get_ports PGOOD_0_75V]

set_property PACKAGE_PIN D14 [get_ports {MCLK[1]}]
set_property PACKAGE_PIN D15 [get_ports {MCLK_N[1]}]
set_property PACKAGE_PIN L1 [get_ports ACLK_MASTER]
set_property PACKAGE_PIN K1 [get_ports ACLK_MASTER_N]
set_property PACKAGE_PIN M4 [get_ports {MCLK[2]}]
set_property PACKAGE_PIN M3 [get_ports {MCLK_N[2]}]

set_property PACKAGE_PIN G21 [get_ports {ACO[0]}]
set_property PACKAGE_PIN G22 [get_ports {ACO_N[0]}]
set_property PACKAGE_PIN H19 [get_ports {ACO[1]}]
set_property PACKAGE_PIN G20 [get_ports {ACO_N[1]}]
set_property PACKAGE_PIN J19 [get_ports {ACO[3]}]
set_property PACKAGE_PIN J20 [get_ports {ACO_N[3]}]
set_property PACKAGE_PIN H20 [get_ports {ACO[2]}]
set_property PACKAGE_PIN H21 [get_ports {ACO_N[2]}]
#set_property PACKAGE_PIN AA6 [get_ports DDR3_SYS_CLK]
#set_property PACKAGE_PIN AB6 [get_ports DDR3_SYS_CLK_N]
set_property PACKAGE_PIN U16 [get_ports {AUX_DATA_IN[0]}]
set_property PACKAGE_PIN V16 [get_ports {AUX_DATA_IN_N[0]}]
set_property PACKAGE_PIN Y18 [get_ports {AUX_DATA_IN[1]}]
set_property PACKAGE_PIN AA18 [get_ports {AUX_DATA_IN_N[1]}]
#set_property PACKAGE_PIN AA17 [get_ports {AUX_DATA_IN[2]}]
#set_property PACKAGE_PIN AB18 [get_ports {AUX_DATA_IN_N[2]}]
#set_property PACKAGE_PIN AA15 [get_ports {AUX_DATA_IN[3]}]
#set_property PACKAGE_PIN AA16 [get_ports {AUX_DATA_IN_N[3]}]

set_property PACKAGE_PIN B13 [get_ports {DATA_OUT[0]}]
set_property PACKAGE_PIN A13 [get_ports {DATA_OUT_N[0]}]
set_property PACKAGE_PIN B14 [get_ports {DATA_OUT[1]}]
set_property PACKAGE_PIN A14 [get_ports {DATA_OUT_N[1]}]
# !debug: for Liron test DATA0/DATA1 pins swapped
#set_property PACKAGE_PIN B14 [get_ports {DATA_OUT[0]}]
#set_property PACKAGE_PIN A14 [get_ports {DATA_OUT_N[0]}]
#set_property PACKAGE_PIN B13 [get_ports {DATA_OUT[1]}]
#set_property PACKAGE_PIN A13 [get_ports {DATA_OUT_N[1]}]

#set_property PACKAGE_PIN A16 [get_ports {DATA_OUT[2]}]
#set_property PACKAGE_PIN A17 [get_ports {DATA_OUT_N[2]}]
#set_property PACKAGE_PIN A18 [get_ports {DATA_OUT[3]}]
#set_property PACKAGE_PIN A19 [get_ports {DATA_OUT_N[3]}]
set_property PACKAGE_PIN W15 [get_ports Aux_Reg_out_P]
set_property PACKAGE_PIN W16 [get_ports Aux_Reg_out_N]
set_property PACKAGE_PIN AB16 [get_ports Aux_Reg_in_P]
set_property PACKAGE_PIN AB17 [get_ports Aux_Reg_in_N]
set_property PACKAGE_PIN F13 [get_ports Diag_out_P]
set_property PACKAGE_PIN F14 [get_ports Diag_out_N]
set_property PACKAGE_PIN H16 [get_ports {DATA1[0]}]
set_property PACKAGE_PIN G16 [get_ports {DATA1_N[0]}]
set_property PACKAGE_PIN J17 [get_ports {DATA1[3]}]
set_property PACKAGE_PIN H18 [get_ports {DATA1_N[3]}]
set_property PACKAGE_PIN H17 [get_ports {DATA1[1]}]
set_property PACKAGE_PIN G17 [get_ports {DATA1_N[1]}]
set_property PACKAGE_PIN L16 [get_ports {DATA2[0]}]
set_property PACKAGE_PIN K17 [get_ports {DATA2_N[0]}]
set_property PACKAGE_PIN K15 [get_ports {DATA2[1]}]
set_property PACKAGE_PIN J15 [get_ports {DATA2_N[1]}]
set_property PACKAGE_PIN K18 [get_ports {DATA2[2]}]
set_property PACKAGE_PIN K19 [get_ports {DATA2_N[2]}]

set_property IOSTANDARD LVCMOS25 [get_ports PGOOD_P1_5V]
set_property IOSTANDARD LVCMOS25 [get_ports PGOOD_1_0V]
set_property IOSTANDARD LVCMOS25 [get_ports PGOOD_1_5V]
set_property IOSTANDARD LVCMOS25 [get_ports PGOOD_1_8V]
set_property IOSTANDARD LVCMOS25 [get_ports PGOOD_2_5V]

set_property PACKAGE_PIN F12 [get_ports Diag_in_P]
set_property PACKAGE_PIN E12 [get_ports Diag_in_N]
set_property PACKAGE_PIN G10 [get_ports Reg_in_P]
set_property PACKAGE_PIN F10 [get_ports Reg_in_N]
set_property PACKAGE_PIN G13 [get_ports Master_Slave]
set_property PACKAGE_PIN G11 [get_ports Reg_out_P]
set_property PACKAGE_PIN F11 [get_ports Reg_out_N]
set_property PACKAGE_PIN B20 [get_ports Buffer_P]
set_property PACKAGE_PIN A20 [get_ports Buffer_N]
set_property PACKAGE_PIN W11 [get_ports Aux_Buffer_P]
set_property PACKAGE_PIN Y11 [get_ports Aux_Buffer_N]
set_property PACKAGE_PIN A9 [get_ports {STATUS_LEDS[0]}]
set_property PACKAGE_PIN E8 [get_ports {STATUS_LEDS[1]}]
set_property PACKAGE_PIN T12 [get_ports Aux_Diag_out_P]
set_property PACKAGE_PIN T13 [get_ports Aux_Diag_out_N]
set_property PACKAGE_PIN U12 [get_ports Aux_Diag_in_P]
set_property PACKAGE_PIN V13 [get_ports Aux_Diag_in_N]
set_property PACKAGE_PIN D7 [get_ports DISABLE_SLAVEn]
#set_property PACKAGE_PIN D8 [get_ports DISABLE_DVDD2n]
#set_property PACKAGE_PIN C5 [get_ports DISABLE_DVDD1n]
set_property PACKAGE_PIN D6 [get_ports DISABLE_ANEGn]
set_property PACKAGE_PIN D5 [get_ports DISABLE_APOSn]
set_property PACKAGE_PIN C6 [get_ports DISABLE_CLK0n]
set_property PACKAGE_PIN C5 [get_ports DISABLE_CLK1n]
set_property PACKAGE_PIN B9 [get_ports PGOOD_1_8V]
set_property PACKAGE_PIN F8 [get_ports PGOOD_1_5V]
set_property PACKAGE_PIN B10 [get_ports PGOOD_2_5V]
set_property PACKAGE_PIN E5 [get_ports PGOOD_0_75V]
set_property PACKAGE_PIN A10 [get_ports PGOOD_P1_5V]
#set_property PACKAGE_PIN F5 [get_ports JTAG_MASTER_SLAVEn]
set_property PACKAGE_PIN G8 [get_ports PGOOD_1_0V]
#set_property PACKAGE_PIN M8 [get_ports PLL_CLKOUT]
#set_property PACKAGE_PIN M7 [get_ports PLL_CLKOUT_N]
set_property PACKAGE_PIN L8 [get_ports RESET]
set_property PACKAGE_PIN D4 [get_ports HEATER_1]
set_property PACKAGE_PIN C4 [get_ports HEATER_2]

set_property PACKAGE_PIN L18 [get_ports {DATA2[3]}]
set_property PACKAGE_PIN L19 [get_ports {DATA2_N[3]}]

set_property PACKAGE_PIN K16 [get_ports {DATA1[2]}]
set_property PACKAGE_PIN J16 [get_ports {DATA1_N[2]}]
set_property PACKAGE_PIN B2 [get_ports {HW_REV[3]}]
set_property PACKAGE_PIN C8 [get_ports {HW_REV[0]}]
set_property PACKAGE_PIN B1 [get_ports {HW_REV[2]}]
set_property PACKAGE_PIN C9 [get_ports {HW_REV[1]}]

set_property PACKAGE_PIN E11 [get_ports Sync_P]
set_property PACKAGE_PIN D11 [get_ports Sync_N]

set_property PACKAGE_PIN V14 [get_ports Aux_Sync_P]
set_property PACKAGE_PIN V15 [get_ports Aux_Sync_N]


set_property PACKAGE_PIN M15 [get_ports TILES_CLK]
set_property PACKAGE_PIN L15 [get_ports TILES_CLK_N]

set_property PACKAGE_PIN N18 [get_ports {ACLK[0]}]
set_property PACKAGE_PIN P20 [get_ports {ACLK[1]}]
set_property PACKAGE_PIN N20 [get_ports {ACLK[2]}]
set_property PACKAGE_PIN N15 [get_ports {ACLK[3]}]
set_property PACKAGE_PIN P21 [get_ports {D_START[0]}]
set_property PACKAGE_PIN P22 [get_ports {D_START[1]}]
set_property PACKAGE_PIN R19 [get_ports {D_START[2]}]
set_property PACKAGE_PIN R20 [get_ports {D_START[3]}]
set_property PACKAGE_PIN T19 [get_ports {RESETn[0]}]
set_property PACKAGE_PIN T20 [get_ports {RESETn[1]}]
set_property PACKAGE_PIN T21 [get_ports {RESETn[2]}]
set_property PACKAGE_PIN T22 [get_ports {RESETn[3]}]
set_property PACKAGE_PIN V20 [get_ports {SCLK[0]}]
set_property PACKAGE_PIN U20 [get_ports {SCLK[1]}]
set_property PACKAGE_PIN U18 [get_ports {SCLK[2]}]
set_property PACKAGE_PIN U19 [get_ports {SCLK[3]}]
set_property PACKAGE_PIN AB19 [get_ports {SDI[0]}]
set_property PACKAGE_PIN AB20 [get_ports {SDI[1]}]
set_property PACKAGE_PIN AB21 [get_ports {SDI[2]}]
set_property PACKAGE_PIN AA21 [get_ports {SDI[3]}]
set_property PACKAGE_PIN W18 [get_ports {SDO[0]}]
set_property PACKAGE_PIN Y19 [get_ports {SDO[1]}]
set_property PACKAGE_PIN AA20 [get_ports {SDO[2]}]
set_property PACKAGE_PIN Y20 [get_ports {SDO[3]}]
set_property PACKAGE_PIN Y22 [get_ports {SYNC[0]}]
set_property PACKAGE_PIN AA22 [get_ports {SYNC[1]}]
set_property PACKAGE_PIN Y21 [get_ports {SYNC[2]}]
set_property PACKAGE_PIN W21 [get_ports {SYNC[3]}]
set_property PACKAGE_PIN W22 [get_ports {SCS1[0]}]
set_property PACKAGE_PIN V21 [get_ports {SCS1[1]}]
set_property PACKAGE_PIN V22 [get_ports {SCS1[2]}]
set_property PACKAGE_PIN U22 [get_ports {SCS1[3]}]
set_property PACKAGE_PIN V18 [get_ports {SCS2[0]}]
set_property PACKAGE_PIN V19 [get_ports {SCS2[1]}]
set_property PACKAGE_PIN R16 [get_ports {SCS2[2]}]
set_property PACKAGE_PIN P17 [get_ports {SCS2[3]}]
set_property PACKAGE_PIN R18 [get_ports {DISCARD[0]}]
set_property PACKAGE_PIN U17 [get_ports {DISCARD[1]}]
set_property PACKAGE_PIN T17 [get_ports {DISCARD[2]}]
set_property PACKAGE_PIN N19 [get_ports {DISCARD[3]}]
set_property PACKAGE_PIN F19 [get_ports {MCLK[0]}]
set_property PACKAGE_PIN F20 [get_ports {MCLK_N[0]}]

set_property PACKAGE_PIN G4 [get_ports {SDA[1]}]
set_property PACKAGE_PIN G3 [get_ports {SDA[0]}]
set_property PACKAGE_PIN F1 [get_ports {SCL[0]}]
set_property PACKAGE_PIN G1 [get_ports {SCL[1]}]
set_property PACKAGE_PIN R17 [get_ports Aux_Sig_2]
set_property PACKAGE_PIN T16 [get_ports Sig_2]

# - bank 14: reserve Flash configuration pins: L14, M15, K17, K18, M13
# 01/02/2023 for remote config:
set_property IOSTANDARD LVCMOS18 [get_ports SO_FLASH]
set_property IOSTANDARD LVCMOS18 [get_ports SI_FLASH]
set_property IOSTANDARD LVCMOS18 [get_ports CS_FLASH]
set_property PACKAGE_PIN M22 [get_ports SO_FLASH]
set_property PACKAGE_PIN M21 [get_ports SI_FLASH]
set_property PACKAGE_PIN N17 [get_ports CS_FLASH]

# 20/12/2021 IODELAY_GROUP
#set_property IODELAY_GROUP IO_DLY1 [get_cells {io_inst_1/delay_main_inst}]
#set_property IODELAY_GROUP IO_DLY1 [get_cells {Buffer_1/inst/pins[0].idelaye2_bus}]
#set_property IODELAY_GROUP IO_DLY1 [get_cells {Diag_in1_inst/inst/pins[0].idelaye2_bus}]
#set_property IODELAY_GROUP IO_DLY1 [get_cells {Reg_in1_1/inst/pins[0].idelaye2_bus}]
#set_property IODELAY_GROUP IO_DLY1 [get_cells {Sync_1/inst/pins[0].idelaye2_bus}]
#set_property IODELAY_GROUP IO_DLY2 [get_cells {io_inst_1/delay_aux_inst}]
#set_property IODELAY_GROUP IO_DLY2 [get_cells {Aux_Diag_in_1/inst/pins[0].idelaye2_bus}]
#set_property IODELAY_GROUP IO_DLY2 [get_cells {Aux_Reg_in1_inst/inst/pins[0].idelaye2_bus}]
# 06/11/2022 IODELAY_GROUP
set_property IODELAY_GROUP ams_rx_in_group [get_cells Tiles_managment_m/ms_gen_1.idelay_rx_inst]
set_property IODELAY_GROUP ams_rx_in_group [get_cells {Tiles_managment_m/Asic_data_gen[*].Asic_data_inst/Phoebe_dat_IF_inst/InDatPhoebe_inst/InputDelay}]
set_property IODELAY_GROUP ams_rx_in_group [get_cells {Tiles_managment_s/Asic_data_gen[*].Asic_data_inst/Phoebe_dat_IF_inst/InDatPhoebe_inst/InputDelay}]
set_property IODELAY_GROUP IO_DLY2 [get_cells io_inst_1/delay_main_inst]
set_property IODELAY_GROUP IO_DLY3 [get_cells io_inst_1/delay_aux_inst]
#set_property IODELAY_GROUP IO_DLY2 [get_cells {io_inst_1/Buffer_1/inst/pins[0].idelaye2_bus}]
set_property IODELAY_GROUP IO_DLY2 [get_cells io_inst_1/RX_series7_1/InputDelay]
#set_property IODELAY_GROUP IO_DLY2 [get_cells {io_inst_1/Reg_in1_1/inst/pins[0].idelaye2_bus}]
set_property IODELAY_GROUP IO_DLY2 [get_cells registers_inst_A/RX_series_COMPONENT/InputDelay]
#set_property IODELAY_GROUP IO_DLY2 [get_cells {io_inst_1/Sync_1/inst/pins[0].idelaye2_bus}]
set_property IODELAY_GROUP IO_DLY2 [get_cells IP_DATAVAL_HEADER_TOP_1/RX_IP_DATAVAL_HEADER_PINS/InputDelay]
#set_property IODELAY_GROUP IO_DLY2 [get_cells {io_inst_1/Diag_in1_inst/inst/pins[0].idelaye2_bus}]
set_property IODELAY_GROUP IO_DLY2 [get_cells registers_inst_B/RX_series_COMPONENT/InputDelay]
set_property IODELAY_GROUP IO_DLY3 [get_cells {io_inst_1/Aux_Diag_in_1/inst/pins[0].idelaye2_bus}]
set_property IODELAY_GROUP IO_DLY3 [get_cells {io_inst_1/Aux_Reg_in1_inst/inst/pins[0].idelaye2_bus}]
#
#create_clock -period 5.000 -name MCLK0 [get_ports {MCLK[0]}]
#create_clock -period 5.000 -name MCLK1 [get_ports {MCLK[1]}]
#create_clock -period 5.000 -name MCLK2 [get_ports {MCLK[2]}]
create_clock -period 5.000 -name MCLK6 [get_ports {MCLK[6]}]
#create_clock -period 5.000 -name DDR3_SYS_CLK [get_ports DDR3_SYS_CLK]
create_clock -period 1501.000 -name ACLK [get_ports ACLK_MASTER]
# !TODO: 04/01/2022 only for test, remove
#set_property PACKAGE_PIN AA14 [get_ports {RECEIVER_CLK_P}]
#set_property PACKAGE_PIN AB14 [get_ports {RECEIVER_CLK_N}]
#create_clock -period 10.000 -name RECEIVER_CLK  [get_ports RECEIVER_CLK_P]
#set_property LOC MMCME2_ADV_X0Y0 [get_cells -hierarchical "*MmcmAlignIo_I_Isrdse2_Clk*" ]
# !debug: 04/12/2022 note: create_clock not need, because clock ports connected to PLL
set_clock_latency -source -early 0.200 [get_clocks {MCLK[0]}]
set_clock_latency -source -late 0.200 [get_clocks {MCLK[0]}]
set_clock_latency -source -early 0.200 [get_clocks {MCLK[1]}]
set_clock_latency -source -late 0.200 [get_clocks {MCLK[1]}]
#set_clock_groups -name all_async -asynchronous #  -group [get_clocks -include_generated_clocks  -of [get_ports {MCLK[0]}] #  -group [get_clocks -include_generated_clocks  -of [get_ports {MCLK[1]}]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks {MCLK[0]}] -group [get_clocks -include_generated_clocks {MCLK[1]}]
set_clock_groups -asynchronous -group CLK50_CLK1_PLL -group ACLK
# 04/09/2024 for tiles data
create clock -name VirtClk_160 -period 6.25
set_input_delay -clock VirtClk_160 2 [get_ports {DATA1[*]}]
set_input_delay -clock VirtClk_160 2 [get_ports {DATA2[*]}]
create clock -name VirtClk_200 -period 5
set_input_delay -clock VirtClk_200 2 [get_ports Sync_P]
set_input_delay -clock VirtClk_200 2 [get_ports Buffer_P]
set_input_delay -clock VirtClk_200 2 [get_ports Diag_in_P]
set_input_delay -clock VirtClk_200 2 [get_ports Reg_in_P]

set_property IOSTANDARD LVDS_25 [get_ports {MCLK[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {MCLK[4]}]
set_property PACKAGE_PIN P15 [get_ports {MCLK[3]}]
set_property PACKAGE_PIN P16 [get_ports {MCLK_N[3]}]
set_property PACKAGE_PIN F7 [get_ports {MCLK[4]}]
set_property PACKAGE_PIN F6 [get_ports {MCLK_N[4]}]
set_property PACKAGE_PIN Y6 [get_ports {MCLK[5]}]
set_property PACKAGE_PIN Y5 [get_ports {MCLK_N[5]}]
set_property PACKAGE_PIN AA14 [get_ports {MCLK[6]}]
set_property PACKAGE_PIN AB14 [get_ports {MCLK_N[6]}]

#set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DEBUG_TP[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports Master_Slave]
set_property PACKAGE_PIN Y13 [get_ports {DEBUG_TP[2]}]
set_property PACKAGE_PIN Y12 [get_ports {DEBUG_TP[3]}]
set_property PACKAGE_PIN J22 [get_ports {DEBUG_TP[5]}]
set_property PACKAGE_PIN J21 [get_ports {DEBUG_TP[4]}]
#set_property PACKAGE_PIN B6 [get_ports {DEBUG_TP[8]}]
set_property PACKAGE_PIN A6 [get_ports {DEBUG_TP[6]}]
set_property PACKAGE_PIN A5 [get_ports {DEBUG_TP[7]}]
set_property PACKAGE_PIN G14 [get_ports {DEBUG_TP[0]}]
set_property PACKAGE_PIN F15 [get_ports {DEBUG_TP[1]}]

# time constrains
#set_property PHASESHIFT_MODE LATENCY [get_cells {io_inst_1/CLK1_PLL_inst/inst/mmcm_adv_inst}]
create_generated_clock -name TILES_CLK -source [get_pins {tiles_if_g[0].dummy_tile_for_pins_1/clk_out_g.ODDR_inst/C}] -divide_by 1 -invert [get_ports TILES_CLK]
# Sync_P/_N
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.080 [get_ports Sync_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.100 [get_ports Sync_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.280 [get_ports Sync_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.300 [get_ports Sync_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.080 [get_ports Sync_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.100 [get_ports Sync_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.280 [get_ports Sync_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.300 [get_ports Sync_N]
# Diag_in_P/_N
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.080 [get_ports Diag_in_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.100 [get_ports Diag_in_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.280 [get_ports Diag_in_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.300 [get_ports Diag_in_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.080 [get_ports Diag_in_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.100 [get_ports Diag_in_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.280 [get_ports Diag_in_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.300 [get_ports Diag_in_N]
# Buffer_P/_N
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.360 [get_ports Buffer_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.400 [get_ports Buffer_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.360 [get_ports Buffer_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.400 [get_ports Buffer_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.360 [get_ports Buffer_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.400 [get_ports Buffer_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.360 [get_ports Buffer_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.400 [get_ports Buffer_P]
# Reg_in_P/_N
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.360 [get_ports Reg_in_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.400 [get_ports Reg_in_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.360 [get_ports Reg_in_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.400 [get_ports Reg_in_N]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -min -add_delay 0.360 [get_ports Reg_in_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -clock_fall -max -add_delay 0.400 [get_ports Reg_in_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -min -add_delay 0.360 [get_ports Reg_in_P]
set_input_delay -clock [get_clocks {MCLK[1]}] -max -add_delay 0.400 [get_ports Reg_in_P]
## for JTAG:
##create_clock -period 6.250 -name VIRTUAL_CLK160_CLK0_PLL -waveform {0.000 3.125}
### tile data
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -min -add_delay 0.260 [get_ports {DATA1[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -max -add_delay 0.300 [get_ports {DATA1[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -min -add_delay 0.260 [get_ports {DATA1_N[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -max -add_delay 0.300 [get_ports {DATA1_N[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -min -add_delay 0.260 [get_ports {DATA2[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -max -add_delay 0.300 [get_ports {DATA2[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -min -add_delay 0.260 [get_ports {DATA2_N[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -max -add_delay 0.300 [get_ports {DATA2_N[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -min -add_delay 0.260 [get_ports {SDO[*]}]
##set_input_delay -clock [get_clocks VIRTUAL_CLK160_CLK0_PLL] -max -add_delay 0.300 [get_ports {SDO[*]}]
# tile data
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -min -add_delay 0.360 [get_ports {DATA1_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -max -add_delay 0.400 [get_ports {DATA1_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -min -add_delay 0.360 [get_ports {DATA1_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -max -add_delay 0.400 [get_ports {DATA1_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -min -add_delay 0.360 [get_ports {DATA1[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -max -add_delay 0.400 [get_ports {DATA1[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -min -add_delay 0.360 [get_ports {DATA1[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -max -add_delay 0.400 [get_ports {DATA1[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -min -add_delay 0.360 [get_ports {DATA2_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -max -add_delay 0.400 [get_ports {DATA2_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -min -add_delay 0.360 [get_ports {DATA2_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -max -add_delay 0.400 [get_ports {DATA2_N[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -min -add_delay 0.360 [get_ports {DATA2[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -clock_fall -max -add_delay 0.400 [get_ports {DATA2[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -min -add_delay 0.360 [get_ports {DATA2[*]}]
set_input_delay -clock [get_clocks {MCLK[0]}] -max -add_delay 0.400 [get_ports {DATA2[*]}]
set_false_path -from [get_clocks {MCLK[0]}] -to [get_cells -hierarchical -filter { PRIMITIVE_TYPE == IO.SERDES.ISERDESE2 }]
set_false_path -from [get_clocks {MCLK[1]}] -to [get_cells -hierarchical -filter { PRIMITIVE_TYPE == IO.SERDES.ISERDESE2 }]
set_false_path -from [get_ports ACLK_MASTER] -to [get_pins {aclk_shr_50m_reg[0]/D}]
set_false_path -from [get_ports ACLK_MASTER] -to [get_pins io_inst_1/aclk_50m_reg/D]
set_false_path -from [get_pins {use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/reading_size_40m_reg[*]/C}] -to [get_pins {use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/reading_size_128m_reg[*]/D}]
set_false_path -from [get_pins use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/SKIP_ECC_reg/C] -to *
set_false_path -from [get_pins use_ddr3_phy_g.ddr_driver_1/ddr3_axi_if_inst/u_DDR3_AXI_IF_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_calib_top/init_calib_complete_reg/C] -to *
set_false_path -from [get_pins use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/header_received_128m_reg/C] -to [get_pins use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/header_received_r0_40m_reg/D]
set_false_path -from * -to [get_pins use_ddr3_phy_g.ddr_driver_1/global_reset_ui_clk_reg/D]
set_false_path -from * -to [get_pins {u_ila_1/inst/PROBE_PIPE.shift_probes_reg[0][*]/D}]
set_false_path -from [get_pins {use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/module_raw_header_reg[*]/C}] -to [get_pins {use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/module_raw_header_r_reg[*]/D}]
set_false_path -from [get_pins {Tiles_managment_m/IP64_vec_reg[4]/C}] -to [get_pins use_ddr3_phy_g.ddr_driver_1/data_sort_ddr3_wr_1/ip_ui_clk_reg/D]
set_false_path -from [get_pins use_ddr3_phy_g.ddr_driver_1/EVOLVING_REQ_PULSE_reg/C] -to [get_pins use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/evolving_req_pulse_64m_reg/D]
set_false_path -from [get_pins use_ddr3_phy_g.ddr_driver_1/REGULAR_REQ_PULSE_reg/C] -to [get_pins use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/regular_req_pulse_64m_reg/D]
set_false_path -from [get_pins IP_DATAVAL_HEADER_TOP_1/fq_stream_enable_reg/C] -to [get_pins fq_stream_enable_ui_clk_reg/D]
set_false_path -from [get_pins use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/fifo4k_full_128m_reg/C] -to [get_pins use_ddr3_phy_g.ddr_driver_1/read_ddr3_rd_1/fifo4k_full_50m_reg/D]
set_false_path -from [get_pins use_ddr3_phy_g.ddr_driver_1/evolving_ddr3_wr_1/error_core_addr_reg/C] -to [get_pins use_ddr3_phy_g.ddr_driver_1/evolving_ddr3_wr_1/error_core_addr_sys_clk_reg/D]
set_false_path -from [get_pins {Tiles_managment_m/Phoebe_CntrlSpiSplitMem_inst/phoebe_cntrlspisplit_inst/spi_ams_gen[1].phoebe_controller_inst/ACLK_and_TILES_CLK_EN_reg/C}] -to [get_pins io_inst_1/ODDR_aclk0_inst/R]
set_false_path -from [get_pins {Tiles_managment_m/Phoebe_CntrlSpiSplitMem_inst/phoebe_cntrlspisplit_inst/spi_ams_gen[1].phoebe_controller_inst/ACLK_and_TILES_CLK_EN_reg/C}] -to [get_pins io_inst_1/ODDR_aclk1_inst/R]
set_false_path -from [get_pins {Tiles_managment_m/Phoebe_CntrlSpiSplitMem_inst/phoebe_cntrlspisplit_inst/spi_ams_gen[1].phoebe_controller_inst/ACLK_and_TILES_CLK_EN_reg/C}] -to [get_pins io_inst_1/ODDR_aclk2_inst/R]
set_false_path -from [get_pins {Tiles_managment_m/Phoebe_CntrlSpiSplitMem_inst/phoebe_cntrlspisplit_inst/spi_ams_gen[1].phoebe_controller_inst/ACLK_and_TILES_CLK_EN_reg/C}] -to [get_pins io_inst_1/ODDR_aclk3_inst/R]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets io_inst_1/aclk_master_i]


set_property MARK_DEBUG false [get_nets memory_buffer_if_1/scan_first_reading]
set_property MARK_DEBUG false [get_nets memory_buffer_if_1/scan_data_valid]
set_property MARK_DEBUG false [get_nets IP_DATAVAL_HEADER_TOP_1/FOOTER_CTRL_1/GOOD_PACKET_RECEIVED]
set_property MARK_DEBUG false [get_nets IP_DATAVAL_HEADER_TOP_1/FOOTER_CTRL_1/DATA_VALID]
set_property MARK_DEBUG false [get_nets latch_test_buffer]
set_property MARK_DEBUG false [get_nets memory_buffer_if_1/first_reading_from_merging]
set_property MARK_DEBUG false [get_nets memory_buffer_if_1/last_reading_from_merging]
set_property MARK_DEBUG false [get_nets registers_inst_B/TX_series7_COMPONENT/fifo_not_empty]
set_property MARK_DEBUG false [get_nets registers_inst_B/S_WR_EN]
set_property MARK_DEBUG false [get_nets registers_inst_B/S_RD_REQ]
set_property MARK_DEBUG false [get_nets registers_inst_B/S_GO]
set_property MARK_DEBUG false [get_nets {registers_inst_A/REGISTER_BANK_A/S_REGISTER_59_reg_n_0_[0]}]
set_property MARK_DEBUG false [get_nets registers_inst_B/TX_series7_COMPONENT/RD_EMPTY]
set_property MARK_DEBUG false [get_nets registers_inst_B/TX_FIFO_INS/full]




set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk]
