###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Mon Sep 19 10:07:47 2022
##  Generated by MIG Version 4.1
##  
##################################################################################################
##  File name :       DDR3_AXI_IF.xdc
##  Details :     Constraints file
##                    FPGA Family:       SPARTAN7
##                    FPGA Part:         XC7S75-FGGA484
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         324.992 MHz
##                    Time Period:       3077 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->IS43TR85120BL-125KBL
## Data Width: 8
## Time Period: 3077
## Data Mask: 1
##################################################################################################